language: objective-c
osx_image: xcode7.3
before_install:
  - gem install xcpretty
script:
  - xcodebuild -version
  - xcodebuild -project Example/Petal.xcodeproj -scheme PetalTests -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Sources'
