language: objective-c
osx_image: xcode7.1
before_install:
  - gem install xcpretty
script:
  - xcodebuild -version
  - xcodebuild -project Example/Petal.xcodeproj -scheme PetalTests -sdk iphonesimulator -destination "OS=9.1,name=iPad 2" -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
  after_success:
  - bash <(curl -s https://codecov.io/bash)
